import { z } from 'zod';

export enum UserRole {
	USER = 'user',
	ADMIN = 'admin',
}

export const userSchema = z.object({
	id: z.string(),
	name: z.string(),
	email: z.email(),
	role: z.enum(UserRole),
	password_hash: z.string().min(6),
	created_at: z.coerce.date().optional(), // must be generated by database
});

export type User = z.infer<typeof userSchema>;
